### ISSUE TITLE
Contact us page:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#10]
Beneath the form, let's increase the space between the "Submit" button and the start of the footer. It's feeling a bit cramped. Especially at a medium-sized/tablet breakpoint.

https://drive.google.com/file/d/18PylOAAFJkl3SMxR1ffiBlPqhgAdWcSz/view?usp=sharing

https://drive.google.com/file/d/18Tx5H6vbDQ4kJp-tGnhlqEpQWyBXaCtc/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jthiel16** [comment]
@jtuckertw @cmoosman1 I'm still seeing a lot of these issues including this one. Am I looking at the correct link? (http://subsalve.wpengine.com/contact)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel Please re-validate and close if good.  Thanks!

**Comment by jthiel16** [comment]
Looks good, thank you
