### ISSUE TITLE
Title of Page gets wonky as does homepage image 

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#116]
Steps to Reproduce
1. Navigate to News
2. Navigate to Applications/see Accessories
3) Navigate to News - Note title of page says "Case Studies" rest of page is News
![image](https://user-images.githubusercontent.com/45019034/68269976-fa7e0780-0018-11ea-987f-8d61205bd4ca.png)

Then navigate to Homepage - Image is incorrect.
![image](https://user-images.githubusercontent.com/45019034/68270002-108bc800-0019-11ea-8645-4ad209524ec3.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@cmoosman1 Final step still shows the weird ocean tundra image.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@cmoosman1 Awesome!  Closed
