### ISSUE TITLE
About us page, in the Our History section:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#2]
An image upload issue ...

In the years 2017 and 2018, the images are coming in off-centered and without a background. We need to size/adjust these images so they aren't transparent and are cropped properly.

https://drive.google.com/file/d/193dSxBSP_OMTUdxj5Jbf1CUSV1hVAaTf/view?usp=sharing

https://drive.google.com/file/d/18uXbZwbBcXDy4w-12wcDAoPdfI0xDPHV/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel Please re-validate and close if good.  Thanks!

**Comment by jthiel16** [comment]
@jtuckertw @cmoosman1 This is still an issue. If you get me access to WP I can take a look at replacing the photos

**Comment by jthiel16** [comment]
The images are updated, closing the ticket
