### ISSUE TITLE
Product detail page (ie, http://subsalve.wpengine.com/aircraft-lift-bags):

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#20]
In section 2 "Built for the Impossible", a couple things:

1) Can we set up these divs so the height auto-adjusts to the amount of content?

That way, there wouldn't be that large gap after the end of the paragraph.

2) Since we're not using a side-by-side paragraph setup here, I'd like to reduce the width of this text container so it's easier to read. 

I think if we reduced the width by 2 columns, that should help.

https://drive.google.com/file/d/17vFETDRjKSnS35vkRZrgCT8riTPFdlvk/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel Please re-validate and close if good.  Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 @jtuckertw 
Number 1 looks resolved
Number 2 is still an issue (see original post)

**Comment by jtuckertw** [comment]
Iphone 7 Test.

Width is cut off  "From boats"  and "with you" are truncated at the margins.

**Comment by cmoosman1** [comment]
@jthiel16 @jtuckertw - these dont have enough content for 2 column layout? Alot of these barely of two sentences

**Comment by jthiel16** [comment]
@cmoosman1 I'm ok with doing a one-column layout (as is), we would just need to narrow the width of that text container to make that copy more legible.

**Comment by jtuckertw** [comment]
Resolved.
