### ISSUE TITLE
News slider component:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#33]
Let's move the left arrow icon over so it's closer to the right icon, about 30px apart should work.

Also, not sure if this is a content issue, but looks like it's adding a "1" and "2" after the year on each post

https://drive.google.com/file/d/17Wdd9Uqcj04OjXGgOnoIRqLxA0PsdynO/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and close if all is good - thanks!

**Comment by jthiel16** [comment]
@cmoosman1 @jtuckertw I'm still seeing the arrow spacing issue

<img width="266" alt="Screen Shot 2019-09-27 at 4 10 50 PM-2" src="https://user-images.githubusercontent.com/35710312/68962361-9b935d80-0791-11ea-9798-b11ccaaa789e.png">

**Comment by jtuckertw** [comment]
Fixed
