### ISSUE TITLE
Home page, in the Case Studies section, a couple layout issues:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#34]
• Let's increase the padding between the text and the image. I'm thinking about 30px

• One of the bottom images is breaking outside of the container. Let's have them auto-crop to the correct size

• The play and view-large icons look fuzzy. Let's use either 2x pngs or svgs

https://drive.google.com/file/d/17S_YH2jnJ4D0ORCvM5Q3EUJ3jLYUwFe-/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jthiel16** [comment]
The image crop looks fixed, but still seeing the padding and fuzzy icon issues. 

The zoom icon also looks off-center, on hover.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel Please re-validate and close if good.  Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 The icons still look low-quality and off-centered

**Comment by jtuckertw** [comment]
@jthiel16 Please re-validate and close if all is good.  Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 The magnifying glass icons still look low-quality and off-centered with the text beneath them

<img width="753" alt="Screen Shot 2019-12-16 at 10 27 37 AM" src="https://user-images.githubusercontent.com/35710312/70924261-d4bc2900-1fee-11ea-8857-d6a86f91b09a.png">
<img width="375" alt="Screen Shot 2019-12-16 at 10 27 43 AM" src="https://user-images.githubusercontent.com/35710312/70924268-d7b71980-1fee-11ea-9e0d-380f8cc8e51f.png">

**Comment by jtuckertw** [comment]
Closing - Issue Still Exists but is minor.
