### ISSUE TITLE
About Us page:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#4]
Has a lot of responsive issues. When viewing on mobile, there are elements going off screen.

And the image gallery isn't working well at any size. It kind've just looks broken with the various sized gaps between images

https://drive.google.com/file/d/18p9D-D-n15CkTNeGu5_wP2ZXEvewL19W/view?usp=sharing

https://drive.google.com/file/d/18okw7-T-qDgl7RYeNnJcHYEKijuUDQcM/view?usp=sharing

https://drive.google.com/file/d/18plqrDFJIfcLsjaiYZYh0tKla07R-_BA/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel Please re-validate and close if good.  Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 The image gallery looks nice. One issue I'm still seeing on mobile:

The text blocks under "Our Mission" are being cut off when viewing on mobile

![IMG_0446](https://user-images.githubusercontent.com/35710312/68700798-ccca1e80-0542-11ea-8dc7-d16e05af0e03.PNG)

**Comment by jtuckertw** [comment]
@jthiel Please re-validate and close if good. Thanks!

**Comment by jthiel16** [comment]
Looks good, closing
