### ISSUE TITLE
Home page, in the "our products" card section:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#40]
At medium screen sizes, the description text breaks out of the container. Recommend either hiding the gray descriptor text at these medium breakpoints OR going to the mobile/stacked layout sooner

https://drive.google.com/file/d/17FCx7PWDNuFj3_Cap3hK4Zd9hO4K5WQz/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Still there.  Steps to recreate, slowly resize browser to the transition before stacking and the issue appears.
![image](https://user-images.githubusercontent.com/45019034/68736637-6bd03400-059e-11ea-8785-2bcfbb29136a.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@cmoosman1 Still happening on resize of windows as described above.

**Comment by jtuckertw** [comment]
Not fixed...lowered priority

**Comment by cmoosman1** [comment]
@jtuckertw - From a responsive perspective I have covered all the break point and a few inbetween. @jthiel16 will need to advise in terms of truncating text or dropping font size.

**Comment by jthiel16** [comment]
I think this is looking better now. Once we get real copy in there let's take another look and make sure it's working ok. I'll close this ticket
