### ISSUE TITLE
Mobile Nav:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#43]
With the nav open, when I tap on "Products" and then try to scroll down to see the list, the nav closes as soon as I touch the screen

**Comment by cmoosman1** [comment]
@jtuckertw  - This is resolved in the current build

**Comment by jtuckertw** [comment]
Issue still happens on iPhone 7.  Menu closes on scroll release not allowing user to click products that are lower than Propeller Bags in the alpha list.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Retest on 12/1 Issue still happens on iPhone 7. Menu closes on scroll release not allowing user to click products that are lower than Propeller Bags in the alpha list.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build.

**Comment by jtuckertw** [comment]
Yes!  Fixed!

**Comment by jtuckertw** [comment]
Issue is back again @cmoosman1

**Comment by jtuckertw** [comment]
Fixed!
