### ISSUE TITLE
The Subsalve and Performance Inflatables logos look low quality in both the main nav bar, and in the footer, viewing on retina display.

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#55]
Let's use either the 2x-sized PNGs, or SVG so they look nice and crisp.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and close if all is good - thanks!

**Comment by jthiel16** [comment]
@cmoosman1 I'm still seeing the issue in the Subsalve main nav bar logo, and the Performance Inflatables logo in the footer.

cc @jtuckertw

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and closed if fixed - thanks!

**Comment by jthiel16** [comment]
Looks good, thank you. Closing ticket
