### ISSUE TITLE
Functionality : The Download Catalog button redirects to Google.com

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#74]
Severity: Major
Location: Homepage
OS / OS Version: Global
Device / Browser: Global
 
Expected Results: 
  When the user clicks the Download Catalog button, the site will redirect to a pdf or a page.
 
Actual Results: 
  When the user clicks the Download Catalog button, the site redirects to Google.com
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/ on any supported device
	2. Scroll down to Download Catalog
	3. Click/Tap Download Catalog
	4. Observe the site redirects too Google.com
 
Notes: N/A

Rate of Reproduction: 100%
![Download Catalog Issue](https://user-images.githubusercontent.com/10537386/66435001-07d7b000-e9e1-11e9-88fa-1c64cc65b6a0.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - This is content @TheNewWallace can you upload the pdf and then add the link in the WP admin?

**Comment by jtuckertw** [comment]
@TheNewWallace Please upload/link the catalog on site.

**Comment by jtuckertw** [comment]
@britnigallello Catalog upload needed, please.

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@cmoosman1 Catalog is still not uploading in Header menu or on the Homepage Download Catalog block

**Comment by jtuckertw** [comment]
Fixed
