### ISSUE TITLE
Visual : The Vehicle Recovery Systems information box, has an error in the text on Mobile

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#78]
Severity: Trivial
Location: http://subsalve.wpengine.com/aircraft-and-vehicle-recovery
OS / OS Version: Global Mobile
Device / Browser: Global Mobile
 
Expected Results: 
  When the user navigates the site, the site will keep consistency on supported devices
 
Actual Results: 
  When the user navigates the site on mobile, the Vehicle Recovery Systems box shows an error in the text
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com/aircraft-and-vehicle-recovery on Google Pixel 3XL
	2. Scroll down to Vehicle Recovery Systems
	3. Observe the error text in the title
 
Notes: N/A

Rate of Reproduction: 100%
![Text Error](https://user-images.githubusercontent.com/10537386/66435164-6ef56480-e9e1-11e9-9a1b-b3f780edf172.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Still exists
![image](https://user-images.githubusercontent.com/45019034/68734279-0a589700-0597-11ea-9bd8-e09c7aa8c160.png)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Error seems resolved on Mobile but still apparent on Desktop

![image](https://user-images.githubusercontent.com/45019034/69935258-8d338a00-1491-11ea-88f3-e74a8c959c60.png)

**Comment by jtuckertw** [comment]
Resolved
