### ISSUE TITLE
Functionality : The Applications page is blank

### ISSUE THREAD

**Issue by adamsisneros** [Tallwave/PIC-Subsalve#80]
Severity: Major
Location: http://subsalve.wpengine.com/applications
OS / OS Version: Global
Device / Browser: Global
 
Expected Results: 
  When the user explores the site, all pages and links are as intended
 
Actual Results: 
  When the user goes to all Applications, the site shows a blank page
 
Steps To Reproduce: 
	1. Launch http://subsalve.wpengine.com on Chrome
	2. Hover over Applications dropdown
	3. Click See All Applications
	4. Observe the site redirects to a blank page
 
Notes: N/A

Rate of Reproduction: 100%
![Blank Page](https://user-images.githubusercontent.com/10537386/66435245-a5cb7a80-e9e1-11e9-8214-bb9868031ade.PNG)

**Comment by cmoosman1** [comment]
@jtuckertw - this is resolved in the current build

**Comment by jtuckertw** [comment]
http://subsalve.wpengine.com/applications is still showing as blank but I am not sure that we intended to have an app page.  need to check site map.

**Comment by cmoosman1** [comment]
@jtuckertw - Make sure you clear your cache or review the changes in incognito.

**Comment by cmoosman1** [comment]
@jtuckertw - There is no link to this page?

**Comment by cmoosman1** [comment]
@jtuckertw - There is no "Application" link or page.

**Comment by jtuckertw** [comment]
Not an issue - Closed
