### ISSUE TITLE
Header Menu (products): Missing Salvage Pontoons - Vertical 

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#87]
From Product Menu

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Still missing Water Load Test Bags and Salvage Pontoons-Vertical

List of Items currently in menu:
Aircraft Lift Bag
Bomb Recovery System
Cable and Pipeline Floats
Commercial Lift Bags
Enclosed Flotation Bags
Enclosed Shallow Water Flotation Bags
Inflat-A-Tank
Lifeboat Davit Test Bags/Kit
Mark V/Orca
Pipe Pluggers
Professional Enclosed Lift Bags
Professional Lift Bags
Propeller Bags
Quad Bags
Rapid Recovery System
Salvage Pontoons

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
Menus now show - closed.
