### ISSUE TITLE
Contact Form Validations and Functionality

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#94]
- [x] Email Verification does not check for “dot”(dev)
- [x] Phone Verification allows “Test”(dev)
- [x] Submit leads to Homepage - no confirmation message (dev)
- [x] Contact Us button is inoperable.(dev)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
- [ ] New Issue: Error message not present for missing dot (should be similar to error message for missing @)

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@cmoosman1 New issues are now appearing on the Contact form.

- [ ] Form does not play nicely with autofill on chrome.   Although my email address is valid it is being rejected .

![image](https://user-images.githubusercontent.com/45019034/69936049-dc7aba00-1493-11ea-816d-04245241a161.png)

**Comment by jtuckertw** [comment]
Not fixed.  Error still appearing on Email field when autofill is used.

**Comment by cmoosman1** [comment]
@jtuckertw - We need to look at this together Im not seeing what you are and still not understanding what you are asking here?

**Comment by cmoosman1** [comment]
@jtuckertw - Per our conversation this morning google autofill throws validation errors and is a known issue. The problem in Chrome browser: it does not allow access to the value of the input field after autofill..

**Comment by jtuckertw** [comment]
Closed - Won't fix - Known browser flaw
